<?php
$parameters = array(
	'cache_path' => '%kernel.root_dir%/cache',
	'log_path' => '%kernel.root_dir%/logs',
	'site_url' => '[[softurl]]',
	'install_source' => 'Softaculous',
	'db_driver' => 'mysqli',
	'db_host' => '[[softdbhost]]',
	'db_table_prefix' => '[[dbprefix]]',
	'db_port' => '3306',
	'db_name' => '[[softdb]]',
	'db_user' => '[[softdbuser]]',
	'db_password' => '[[softdbpass]]',
	'db_path' => null,
	'mailer_from_name' => '[[admin_fname]] [[admin_lname]]',
	'mailer_from_email' => '[[admin_email]]',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '[[secret_key]]',
);
