<?php
// Automatically Generated by TestLink Installer - [[date_generated]]
define('DB_TYPE', 'mysql');
define('DB_USER', '[[softdbuser]]');
define('DB_PASS', '[[softdbpass]]');
define('DB_HOST', '[[softdbhost]]');
define('DB_NAME', '[[softdb]]');
define('DB_TABLE_PREFIX', '[[dbprefix]]');
