<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		[[generator]]
 * Date [[date_at]]
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLGRPGenDate is an internal mark
   $CLGRPGenDate = "[[timestamp]]";

/* multiGroupAllowed : Allow teachers to subscribe a user in several groups */
$GLOBALS['multiGroupAllowed'] = TRUE;


/* tutorCanBeSimpleMemberOfOthersGroupsAsStudent : A tutor attached to a group can subscribe himself to another group as a simple user. */
$GLOBALS['tutorCanBeSimpleMemberOfOthersGroupsAsStudent'] = FALSE;


/* showTutorsInGroupList : Not implemented, name reserved  for future version of Claroline */
$GLOBALS['showTutorsInGroupList'] = FALSE;



?>