<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		[[generator]]
 * Date [[date_at]]
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLLNPGenDate is an internal mark
   $CLLNPGenDate = "[[timestamp]]";

/* maxFilledSpace_for_import : Disk space allowed to import scorm package */
$GLOBALS['maxFilledSpace_for_import'] = 100000000;


/* cllnp_resetByUserAllowed : Set to Yes to allow students to reset their progression in learning pathes */
$GLOBALS['cllnp_resetByUserAllowed'] = FALSE;



?>