<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		[[generator]]
 * Date [[date_at]]
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLMSGGenDate is an internal mark
   $CLMSGGenDate = "[[timestamp]]";

/* messagePerPage : Number of message per page */
$GLOBALS['messagePerPage'] = 15;


/* mailNotification : Enable Email notification */
$GLOBALS['mailNotification'] = TRUE;



?>