<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		[[generator]]
 * Date [[date_at]]
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLWIKIGenDate is an internal mark
   $CLWIKIGenDate = "[[timestamp]]";

/* showWikiEditorToolbar : Show wiki syntax toolbar */
$GLOBALS['showWikiEditorToolbar'] = TRUE;


/* forcePreviewBeforeSaving : Force text preview before saving it */
$GLOBALS['forcePreviewBeforeSaving'] = FALSE;



?>