<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		[[generator]]
 * Date [[date_at]]
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLRSSGenDate is an internal mark
   $CLRSSGenDate = "[[timestamp]]";

/* enableRssInCourse : Enable RSS in course */
$GLOBALS['enableRssInCourse'] = TRUE;


/* rssRepositoryCache : Note :  this repository should be protected with a .htaccess or       be placed outside the web. Because there contain data of private courses. */
$GLOBALS['rssRepositoryCache'] = 'tmp/cache/rss/';


/* rssUseCache : Enabling the cache may increase performance */
$GLOBALS['rssUseCache'] = TRUE;


/* rssCacheLifeTime : Time before really compute data. 86400 = 1 day. */
$GLOBALS['rssCacheLifeTime'] = 86400;



?>