<?php

/**
 * -----------------------------------------------------------------------------
 * Generated [[Generated_time]]
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => '[[site_name]]',
    'locale' => '[[language]]',
    'version_installed' => '5.7.5.8',
    'misc' => array(
        'access_entity_updated' => [[timestamp]],
    ),
    'i18n' => array(

        'choose_language_login' => null
    
    )
);
