.hgignore
.hgtags
README.txt
apple-touch-icon.png
archive
courses
documentation
dokeos_license.txt
favicon-blue.ico
favicon.ico
home
index.php
main
news_list.php
plugin
searchdb
tablet_user_portal.php
tests
user_portal.php
user_portal_classic.php
user_portal_classic_ori.php
user_portal_widget.php
webchatdeny.php
whoisonline.php
whoisonlinesession.php